create table profile (
  id                    uuid primary key default gen_random_uuid(),
  full_name             text not null,
  short_name            text not null,
  role                  jsonb not null,
  lead                  jsonb not null,
  status_label          jsonb not null,
  is_open_to_work       boolean not null default true,
  hero_badges           jsonb not null default '[]'::jsonb,
  experience_start_date date not null,
  avatar_url            text,
  photo_url             text,
  email                 text not null,
  linkedin_url          text,
  github_url            text,
  contact_title         jsonb not null,
  contact_lead          jsonb not null,
  meta_title            jsonb not null,
  meta_description      jsonb not null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  is_singleton          boolean generated always as (true) stored,
  constraint profile_singleton unique (is_singleton),
  constraint profile_role_locales check (role ? 'es' and role ? 'en'),
  constraint profile_lead_locales check (lead ? 'es' and lead ? 'en'),
  constraint profile_status_locales check (status_label ? 'es' and status_label ? 'en'),
  constraint profile_contact_title_locales check (contact_title ? 'es' and contact_title ? 'en'),
  constraint profile_contact_lead_locales check (contact_lead ? 'es' and contact_lead ? 'en'),
  constraint profile_meta_title_locales check (meta_title ? 'es' and meta_title ? 'en'),
  constraint profile_meta_description_locales check (meta_description ? 'es' and meta_description ? 'en')
);
